org.gradle.jvmargs=-Xmx4G -Duser.language=en -Duser.country=US -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12
minecraft_version=1.21.10
minecraft_version_range=[1.21.10]
neo_version=21.10.64
mod_id=naven
mod_name=Naven-Modern
mod_license=All Rights Reserved
mod_version=1
mod_group_id=tech.naven
mod_authors=Huty
mod_description=Naven
